# Generated by Django 2.1b1 on 2018-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('apple', 'IOS'), ('android', 'Android'), ('windows', 'Windows')], max_length=16, null=True),
        ),
    ]
